spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/demo
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jwt:
    secret-key: de09bf3207be008eedc9e687175d0f6d367acf6892ed56731845dde1fc42fe433ac213ef82460226289b97fa2013848eab0d8a977a16193b3774879c0411d19b
    password: hiek2001codinglikeithiek2001codinglikeit


  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 1000 #최적화 옵션

logging:
  level:
    org.hibernate.SQL: debug
  pattern:
    console: "%-5level %d{yyyy-MM-dd HH:mm:ss}[%thread] [%F - %M] [%logger{0}:%line] - %msg%n"